further refinements

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -17,7 +17,9 @@ jobs:
           github-token: ${{ secrets.GITHUB_TOKEN }}
       - name: then
         if: steps.when.outputs.created-at != ''
-        run: exit 1
+        run: |
+          echo "::error::Timestamp should be empty" 
+          exit 1
         continue-on-error: true
   creation-enabled:
     name: Sets created-at date by default
@@ -32,5 +34,7 @@ jobs:
           github-token: ${{ secrets.GITHUB_TOKEN }}
       - name: then
         if: steps.when.outputs.created-at == ''
-        run: exit 1
+        run: |
+          echo "::error::Timestamp should not be empty"
+          exit 1
         continue-on-error: true
