Finally work as one step.

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -3,8 +3,7 @@ name: Test
 on: push
 
 jobs:
-  creation-enabled:
-    name: Sets created-at date by default
+  outputs-timestamps:
     runs-on: ubuntu-latest
     steps:
       - name: given
@@ -14,8 +13,20 @@ jobs:
         uses: ./
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
-      - name: then
+      - name: then created as timestamp is not empty
         if: steps.when.outputs.created-at == ''
         run: |
-          echo "::error::Timestamp should not be empty"
+          echo "::error::Created at timestamp must not be empty"
+          exit 1
+        continue-on-error: true
+      - name: then pushed at as timestamp is not empty
+        if: steps.when.outputs.pushed-at == ''
+        run: |
+          echo "::error::Pushed at timestamp must not be empty"
+          exit 1
+        continue-on-error: true
+      - name: then updated at timestamp is not empty
+        if: steps.when.outputs.updated-at == ''
+        run: |
+          echo "::error::Updated at timestamp must not be empty"
           exit 1
